baseURL = "https://slippery-seagull.netlify.app/"
languageCode = "en-us"
title = "Let's Talk about Sex, Baby!"
theme = "hugo-swift-theme"

[markup]
[markup.tableOfContents]
    startLevel = 2
    endLevel = 2